/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6W5g6yqcia275BYzRRyyZM
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsr3R0LHfWnp5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: r3r0lHf_Wnp5/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsr3R0LHfWnp5
});
